import "./Dashboard.css";
import CircularProgress from "../CircularProgress/CircularProgress";
import SkillGap from "../SkillGap/SkillGap";
import JobRecommendations from "../JobRecommendations/JobRecommendations";
import LearningRoadmap from "../LearningRoadmap/LearningRoadmap";
import Analytics from "../Analytics/Analytics";

function Dashboard({ data }) {

  if (!data) return null;

  console.log(JSON.stringify(data, null, 2));

  const jobs = Array.isArray(data.jobMatch)
    ? data.jobMatch
    : [
      {
        role: "AI Engineer",
        match: 90
      },
      {
        role: "Backend Developer",
        match: 84
      },
      {
        role: "Full Stack Developer",
        match: 81
      }
    ];

  const roadmap = Array.isArray(data.learningRoadmap)
    ? data.learningRoadmap
    : [
      "Practice DSA",
      "Master SQL",
      "Learn React & Flask",
      "Build Portfolio Projects",
      "Practice Interviews"
    ];

  const missingSkills = Array.isArray(data.missingSkills)
    ? data.missingSkills
    : [
      "Docker",
      "AWS",
      "CI/CD",
      "System Design"
    ];

  const rewriteSuggestions = Array.isArray(data.resumeRewriteSuggestions)
    ? data.resumeRewriteSuggestions
    : [];



  return (

    <>

      {data.fallback && (

        <div
          style={{
            background: "#fff3cd",
            color: "#856404",
            border: "1px solid #ffeeba",
            padding: "15px",
            margin: "20px",
            borderRadius: "8px",
            textAlign: "center",
            fontWeight: "600"
          }}
        >
          ⚠ AI service is temporarily unavailable.
          <br />
          Showing fallback analysis generated by the application.
        </div>

      )}

      <section className="dashboard">

        <h2>Resume Dashboard</h2>

        <div className="dashboard-grid">

          <div className="dashboard-card">

            <CircularProgress
              value={data.resumeScore}
              title="Resume Score"
              color="#2563eb"
            />

          </div>

          <div className="dashboard-card">

            <CircularProgress
              value={data.atsScore}
              title="ATS Score"
              color="#22c55e"
            />

          </div>

          <div className="dashboard-card">

            <CircularProgress
              value={data.interviewReadiness || 80}
              title="Interview Readiness"
              color="#f59e0b"
            />

          </div>

          <div className="dashboard-card">

            <h3>💰 Expected Salary</h3>

            <h1>
              {data.salaryPrediction || "₹6 - ₹9 LPA"}
            </h1>

          </div>

          <div className="dashboard-card strengths">

            <h3>💪 Strengths</h3>

            <ul>

              {(data.strengths || []).map((item, index) => (

                <li key={index}>
                  ✅ {item}
                </li>

              ))}

            </ul>

          </div>

          <div className="dashboard-card weaknesses">

            <h3>⚠ Weaknesses</h3>

            <ul>

              {(data.weaknesses || []).map((item, index) => (

                <li key={index}>
                  ❌ {item}
                </li>

              ))}

            </ul>

          </div>

          <div className="dashboard-card">

            <h3>📚 Missing Skills</h3>

            <ul>

              {missingSkills.map((item, index) => (

                <li key={index}>
                  📌 {item}
                </li>

              ))}

            </ul>

          </div>

          <div className="dashboard-card">

            <h3>🎯 Best Job Matches</h3>

            <ul>

              {jobs.map((job, index) => (

                <li key={index}>

                  <strong>
                    {job.role}
                  </strong>

                  <br />

                  Match : {job.match}%

                </li>

              ))}

            </ul>

          </div>

        </div>

      </section>

      {rewriteSuggestions.length > 0 && (

        <section className="dashboard">

          <h2>📝 Resume Rewrite Suggestions</h2>

          <div className="dashboard-grid">

            {rewriteSuggestions.map((item, index) => (

              <div
                className="dashboard-card"
                key={index}
              >

                <h3>Original</h3>

                <p>

                  {item.original}

                </p>

                <hr
                  style={{
                    margin: "20px 0"
                  }}
                />

                <h3>Improved</h3>

                <p>

                  {item.improved}

                </p>

              </div>

            ))}

          </div>

        </section>

      )}

      <SkillGap
        strengths={data.strengths}
        weaknesses={data.weaknesses}
      />

      <JobRecommendations
        jobs={jobs}
      />

      <LearningRoadmap
        roadmap={roadmap}
      />

      {/* <Analytics data={data} /> */}

    </>

  );

}

export default Dashboard;